name: launcher_bootstrap
description: Программа для предзагрузки лаунчера написанного на Java (Gravit) со встроенной загрузкой Java.
version: 1.1.1
repository: https://github.com/Qwertbun/LauncherBootstrap

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  archive: ^3.5.1
  http: ^1.2.1
flutter:    
  sdk: flutter    
cupertino_icons: ^0.1.2    
flutter_launcher_icons: ^0.7.2+1**

dev_dependencies:
  json_serializable: ^6.8.0
  lints: ^3.0.0
  
flutter:
  assets:
    - favicon.ico
flutter_icons:    
 android: "launcher_icon"
 ios: true
 image_path: "favicon.ico"
